# Generated by Django 2.2.4 on 2020-05-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0003_auto_20200517_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.CharField(max_length=45),
        ),
    ]
